version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
